In [5]:
import pandas as pd

In [12]:
amd_file = "https://raw.githubusercontent.com/dany-roman/project_4_stock_analysis/main/data/AMD_stock.csv"
google_file = "https://raw.githubusercontent.com/dany-roman/project_4_stock_analysis/main/data/Google_stock.csv"
hp_file = "https://raw.githubusercontent.com/dany-roman/project_4_stock_analysis/main/data/HP_stock.csv"
intel_file = "https://raw.githubusercontent.com/dany-roman/project_4_stock_analysis/main/data/Intel_stock.csv"
tesla_file = "https://raw.githubusercontent.com/dany-roman/project_4_stock_analysis/main/data/Tesla_stock.csv"

amd = pd.read_csv(amd_file)
google = pd.read_csv(google_file)
hp = pd.read_csv(hp_file)
intel = pd.read_csv(intel_file)
tesla = pd.read_csv(tesla_file)

In [25]:
tech_list = [amd, google, hp, intel, tesla]

def cal_test_data(df):
    hc = df['High'] - df['Low']
    oc = df['Close'] - df['Open']
    m_avg_7 = hc.rolling(7, min_periods=0).mean() 
    m_avg_14 = hc.rolling(14, min_periods=0).mean()
    m_avg_21 = hc.rolling(21, min_periods=0).mean()
    m_std_7 = df['Close'].rolling(7, min_periods=0).std()
    close = df['Close']
    test_data = {
        "High-Low Price": hc,
        "Close-Open Price": oc,
        "7-day m_avg": m_avg_7,
        "14-day m_avg": m_avg_14,
        "21-day m_avg": m_avg_21,
        "7-day m_std": m_std_7,
        "Close": close,
    }
    test_df = pd.DataFrame(test_data)
    test_df = test_df.fillna(0)
    return test_df

In [26]:
cal_test_data(amd)
cal_test_data(amd).fillna(0)

      High-Low Price  Close-Open Price  ...  7-day m_std      Close
0           0.629999          0.010000  ...     0.000000  11.430000
1           0.280001         -0.020000  ...     0.000000  11.430000
2           0.460000         -0.190001  ...     0.109697  11.240000
3           0.380000          0.030000  ...     0.092557  11.320000
4           0.330000          0.120000  ...     0.100350  11.490000
...              ...               ...  ...          ...        ...
1002        1.200005          0.009995  ...     2.298816  91.809998
1003        2.320000         -1.330002  ...     2.138821  91.599998
1004        3.029999         -1.040001  ...     1.749579  90.620003
1005        2.659996          1.510002  ...     0.934162  92.290001
1006        1.430000         -0.389999  ...     0.773520  91.709999

[1007 rows x 7 columns]

In [27]:
cal_test_data(google)
cal_test_data(google).fillna(0)

      High-Low Price  Close-Open Price  ...  7-day m_std        Close
0          13.830017          7.330017  ...     0.000000   786.140015
1           8.180054         -1.459961  ...     0.537408   786.900024
2           9.459961          7.940002  ...     4.346769   794.020020
3          15.696045         10.890015  ...     9.271221   806.150024
4           7.135986          0.250000  ...    10.004890   806.650024
...              ...               ...  ...          ...          ...
1002       16.890015          3.849976  ...    12.922782  1738.849976
1003       44.393066         24.454956  ...    17.155756  1776.089966
1004       36.349976        -29.070068  ...    18.298864  1758.719971
1005       39.494995        -22.489990  ...    17.652768  1739.520020
1006       23.510010         16.459961  ...    17.731727  1751.880005

[1007 rows x 7 columns]

In [28]:
cal_test_data(hp)
cal_test_data(google).fillna(0)

      High-Low Price  Close-Open Price  ...  7-day m_std        Close
0          13.830017          7.330017  ...     0.000000   786.140015
1           8.180054         -1.459961  ...     0.537408   786.900024
2           9.459961          7.940002  ...     4.346769   794.020020
3          15.696045         10.890015  ...     9.271221   806.150024
4           7.135986          0.250000  ...    10.004890   806.650024
...              ...               ...  ...          ...          ...
1002       16.890015          3.849976  ...    12.922782  1738.849976
1003       44.393066         24.454956  ...    17.155756  1776.089966
1004       36.349976        -29.070068  ...    18.298864  1758.719971
1005       39.494995        -22.489990  ...    17.652768  1739.520020
1006       23.510010         16.459961  ...    17.731727  1751.880005

[1007 rows x 7 columns]

In [29]:
cal_test_data(intel)
cal_test_data(intel).fillna(0)

      High-Low Price  Close-Open Price  ...  7-day m_std      Close
0           0.660000         -0.010002  ...     0.000000  36.599998
1           0.430000         -0.299999  ...     0.134349  36.410000
2           0.410000         -0.100002  ...     0.130512  36.349998
3           0.490002         -0.110001  ...     0.107393  36.480000
4           0.410000          0.130001  ...     0.114674  36.610001
...              ...               ...  ...          ...        ...
1002        0.750000          0.470001  ...     2.079478  47.070000
1003        0.779999         -0.119999  ...     1.529618  47.070000
1004        4.179996          2.169998  ...     1.083757  49.389999
1005        0.629997         -0.360001  ...     1.242216  48.750000
1006        1.469997          1.070000  ...     1.457073  49.820000

[1007 rows x 7 columns]

In [30]:
cal_test_data(tesla)
cal_test_data(tesla).fillna(0)

      High-Low Price  Close-Open Price  ...  7-day m_std       Close
0           0.392500          0.087500  ...     0.000000   29.037500
1           0.190001          0.042500  ...     0.022982   29.004999
2           0.262501          0.172501  ...     0.077500   29.152500
3           0.422501          0.282501  ...     0.215739   29.477501
4           0.372499          0.260000  ...     0.319441   29.747499
...              ...               ...  ...          ...         ...
1002        2.360001          0.649994  ...     2.123658  131.970001
1003        3.830002          2.699997  ...     3.300767  136.690002
1004        4.449997         -3.180008  ...     3.487737  134.869995
1005        2.590012         -1.860001  ...     2.763909  133.720001
1006        3.020004         -1.389999  ...     1.989628  132.690002

[1007 rows x 7 columns]

In [31]:
cal_test_data(amd).to_csv("test_data/test_amd.csv", index=False, header=True)
cal_test_data(google).to_csv("test_data/test_google.csv", index=False, header=True)
cal_test_data(hp).to_csv("test_data/test_hp.csv", index=False, header=True)
cal_test_data(intel).to_csv("test_data/test_intel.csv", index=False, header=True)
cal_test_data(tesla).to_csv("test_data/test_tesla.csv", index=False, header=True)

FileNotFoundError: ignored

In [33]:
%pip install yahoo_finance

Collecting yahoo_finance
  Downloading yahoo-finance-1.4.0.tar.gz (8.9 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from yahoo_finance) (2018.9)
Collecting simplejson
  Downloading simplejson-3.17.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (129 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 129 kB 6.9 MB/s
Building wheels for collected packages: yahoo-finance
  Building wheel for yahoo-finance (setup.py) ... done
  Created wheel for yahoo-finance: filename=yahoo_finance-1.4.0-py3-none-any.whl size=7231 sha256=8cbb27c7a856d6f2b4a9f1aa47fa8986fe0907f07ab399b756e1006502d89073
  Stored in directory: /root/.cache/pip/wheels/74/3c/6e/504622cec9991612b9e3945fe8b375fef727854b42eb333c91
Successfully built yahoo-finance
Installing collected packages: simplejson, yahoo-finance
Successfully installed simplejson-3.17.5 yahoo-finance-1.4.0

In [42]:
% pip install yfinance

Collecting yfinance
  Downloading yfinance-0.1.63.tar.gz (26 kB)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.23.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.9)
Collecting lxml>=4.5.1
  Downloading lxml-4.6.3-cp37-cp37m-manylinux2014_x86_64.whl (6.3 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 6.3 MB 10.3 MB/s
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2021.5.30)
Building wheels for collected packages: yfinance
  Building wheel for yfinance (setup.py) ... done
  Created wheel for yfinance: filename=yfinance-0.1.63-py2.py3-none-any.whl size=23918 sha256=919c78e08016940de657ca1cd2368e4c5c1d21facf52110f41fca8ede8a353aa
  Stored in directory: /root/.cache/pip/wheels/fe/87/8b/7ec24486e001d3926537f5f7801f57a74d181be25b11157983
Successfully built yfinance
Installing collected packages: lxml, yfinance
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
Successfully installed lxml-4.6.3 yfinance-0.1.63

In [38]:
# from yahoo_finance import Share

In [43]:
import yfinance as yf

In [45]:
google = yf.Ticker("GOOG")
google

yfinance.Ticker object <GOOG>

In [46]:
google.info

{'52WeekChange': 0.7935896,
 'SandP52WeekChange': 0.26372707,
 'address1': '1600 Amphitheatre Parkway',
 'algorithm': None,
 'annualHoldingsTurnover': None,
 'annualReportExpenseRatio': None,
 'ask': 2728.99,
 'askSize': 1000,
 'averageDailyVolume10Day': 1263971,
 'averageVolume': 1045325,
 'averageVolume10days': 1263971,
 'beta': 1.004366,
 'beta3Year': None,
 'bid': 2726.01,
 'bidSize': 900,
 'bookValue': 355.83,
 'category': None,
 'circulatingSupply': None,
 'city': 'Mountain View',
 'companyOfficers': [],
 'country': 'United States',
 'currency': 'USD',
 'currentPrice': 2729.25,
 'currentRatio': 3.152,
 'dateShortInterest': 1631664000,
 'dayHigh': 2741.42,
 'dayLow': 2667.7002,
 'debtToEquity': 11.829,
 'dividendRate': None,
 'dividendYield': None,
 'earningsGrowth': 1.691,
 'earningsQuarterlyGrowth': 1.662,
 'ebitda': 75552997376,
 'ebitdaMargins': 0.34300998,
 'enterpriseToEbitda': 22.659,
 'enterpriseToRevenue': 7.772,
 'enterpriseValue': 1711978840064,
 'exDividendDate': None,
 'exchange': 'NMS',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'expireDate': None,
 'fiftyDayAverage': 2829.48,
 'fiftyTwoWeekHigh': 2936.41,
 'fiftyTwoWeekLow': 1436,
 'financialCurrency': 'USD',
 'fiveYearAverageReturn': None,
 'fiveYearAvgDividendYield': None,
 'floatShares': 580703516,
 'forwardEps': 105.81,
 'forwardPE': 25.793877,
 'freeCashflow': 44609626112,
 'fromCurrency': None,
 'fullTimeEmployees': 144056,
 'fundFamily': None,
 'fundInceptionDate': None,
 'gmtOffSetMilliseconds': '-14400000',
 'grossMargins': 0.55723,
 'grossProfits': 97795000000,
 'heldPercentInsiders': 0.00043000001,
 'heldPercentInstitutions': 0.67146003,
 'impliedSharesOutstanding': 666755008,
 'industry': 'Internet Content & Information',
 'isEsgPopulated': False,
 'lastCapGain': None,
 'lastDividendDate': None,
 'lastDividendValue': None,
 'lastFiscalYearEnd': 1609372800,
 'lastMarket': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'logo_url': 'https://logo.clearbit.com/abc.xyz',
 'longBusinessSummary': 'Alphabet Inc. provides online advertising services in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. The company offers performance and brand advertising services. It operates through Google Services, Google Cloud, and Other Bets segments. The Google Services segment provides products and services, such as ads, Android, Chrome, hardware, Google Maps, Google Play, Search, and YouTube, as well as technical infrastructure; and digital content. The Google Cloud segment offers infrastructure and data analytics platforms, collaboration tools, and other services for enterprise customers. The Other Bets segment sells internet and TV services, as well as licensing and research and development services. The company was founded in 1998 and is headquartered in Mountain View, California.',
 'longName': 'Alphabet Inc.',
 'market': 'us_market',
 'marketCap': 1820297789440,
 'maxAge': 1,
 'maxSupply': None,
 'messageBoardId': 'finmb_29096',
 'morningStarOverallRating': None,
 'morningStarRiskRating': None,
 'mostRecentQuarter': 1625011200,
 'navPrice': None,
 'netIncomeToCommon': 62928998400,
 'nextFiscalYearEnd': 1672444800,
 'numberOfAnalystOpinions': 9,
 'open': 2671.09,
 'openInterest': None,
 'operatingCashflow': 80858996736,
 'operatingMargins': 0.28448,
 'payoutRatio': 0,
 'pegRatio': 1.17,
 'phone': '650-253-0000',
 'previousClose': 2665.31,
 'priceHint': 2,
 'priceToBook': 7.6700954,
 'priceToSalesTrailing12Months': 8.264126,
 'profitMargins': 0.2857,
 'quickRatio': 3.027,
 'quoteType': 'EQUITY',
 'recommendationKey': 'buy',
 'recommendationMean': 1.6,
 'regularMarketDayHigh': 2741.42,
 'regularMarketDayLow': 2667.7002,
 'regularMarketOpen': 2671.09,
 'regularMarketPreviousClose': 2665.31,
 'regularMarketPrice': 2729.25,
 'regularMarketVolume': 1419365,
 'returnOnAssets': 0.12759,
 'returnOnEquity': 0.2829,
 'revenueGrowth': 0.616,
 'revenuePerShare': 326.656,
 'revenueQuarterlyGrowth': None,
 'sector': 'Communication Services',
 'sharesOutstanding': 320168000,
 'sharesPercentSharesOut': 0.004,
 'sharesShort': 2636694,
 'sharesShortPreviousMonthDate': 1628812800,
 'sharesShortPriorMonth': 2589529,
 'shortName': 'Alphabet Inc.',
 'shortPercentOfFloat': None,
 'shortRatio': 2.79,
 'startDate': None,
 'state': 'CA',
 'strikePrice': None,
 'symbol': 'GOOG',
 'targetHighPrice': 3425,
 'targetLowPrice': 2700,
 'targetMeanPrice': 3106.11,
 'targetMedianPrice': 3100,
 'threeYearAverageReturn': None,
 'toCurrency': None,
 'totalAssets': None,
 'totalCash': 135863001088,
 'totalCashPerShare': 203.768,
 'totalDebt': 28100999168,
 'totalRevenue': 220265005056,
 'tradeable': False,
 'trailingAnnualDividendRate': None,
 'trailingAnnualDividendYield': None,
 'trailingEps': 92.187,
 'trailingPE': 29.605585,
 'twoHundredDayAverage': 2527.3582,
 'volume': 1419365,
 'volume24Hr': None,
 'volumeAllCurrencies': None,
 'website': 'http://www.abc.xyz',
 'yield': None,
 'ytdReturn': None,
 'zip': '94043'}

In [47]:
google.cashflow

                                             2020-12-31  ...    2017-12-31
Investments                               -9.822000e+09  ... -1.944800e+10
Change To Liabilities                      1.329000e+09  ...  1.121000e+09
Total Cashflows From Investing Activities -3.277300e+10  ... -3.140100e+10
Net Borrowings                             9.661000e+09  ... -8.600000e+07
Total Cash From Financing Activities      -2.440800e+10  ... -8.298000e+09
Change To Operating Activities             5.813000e+09  ...  3.682000e+09
Net Income                                 4.026900e+10  ...  1.266200e+10
Change In Cash                             7.967000e+09  ... -2.203000e+09
Repurchase Of Stock                       -3.114900e+10  ... -4.846000e+09
Effect Of Exchange Rate                    2.400000e+07  ...  4.050000e+08
Total Cash From Operating Activities       6.512400e+10  ...  3.709100e+10
Depreciation                               1.367900e+10  ...  6.899000e+09
Other Cashflows From Investing Activities  6.800000e+07  ...  1.419000e+09
Change To Account Receivables             -6.524000e+09  ... -3.768000e+09
Other Cashflows From Financing Activities -2.920000e+09  ... -3.366000e+09
Change To Netincome                        9.349000e+09  ...  8.284000e+09
Capital Expenditures                      -2.228100e+10  ... -1.318400e+10

[17 rows x 4 columns]

In [50]:
google.

AttributeError: ignored

In [41]:
amd = Share('AMD')
# google = Share ('GOOG')

URLError: ignored